ezpublish:
    # Repositories configuration, setup default repository to support solr if enabled
    repositories:
        default:
            storage: ~
            search:
                engine: %search_engine%
                connection: default

    # Siteaccess configuration, with one siteaccess per default
    siteaccess:
        list: [%frontend_siteaccess%, %admin_siteaccess%]
        groups:
            site_group: [%frontend_siteaccess%]
        default_siteaccess: %frontend_siteaccess%
        match:
            URIElement: 1

    # System settings, grouped by siteaccess and/or siteaccess group
    system:
        site_group:
            languages: [eng-GB, esl-ES]

ez_publish_legacy:
    system:
        %admin_siteaccess%:
           legacy_mode: true
